blueprint:
  name: Cover control with IKEA TRÅDFRI open/close remote
  description: |
    Control a cover with an IKEA TRÅDFRI open/close button remote over ZHA

    Short press on open/☼ button will open the cover in steps of 5%.
    Short press on close/☰ button will close the cover in steps of 5%.
    Long press on ☼ or ☰  will stop the cover.
  domain: automation
  input:
    remote:
      name: Remote
      description: "IKEA TRÅDFRI open/close remote to use"
      selector:
        device:
          integration: zha
          manufacturer: "IKEA of Sweden"
          model: "TRADFRI open/close remote"
    cover:
      name: Cover
      description: The cover to control
      selector:
        target:
          entity:
            domain: cover
    increment:
      name: Increments in %
      default: 5
      selector:
        number:
          min: 5.0
          max: 100.0
          unit_of_measurement: '%'
          mode: slider
          step: 5.0
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input remote
action:
- choose:
  - conditions:
    - '{{ trigger.event.data.command == "up_open" }}'
    sequence:
    - service: cover.set_cover_position
      target: !input cover
      data:
        position: "{{ state_attr(!input cover, 'current_position') + !input increment }}"
  - conditions:
    - '{{ trigger.event.data.command == "down_close" }}'
    sequence:
    - service: cover.set_cover_position
      target: !input cover
      data:
        position: "{{ state_attr(!input cover, 'current_position') - !input increment }}"
  - conditions:
    - '{{ trigger.event.data.command in ("stop", "stop_opening", "stop_closing") }}'
    sequence:
    - service: cover.stop_cover
      target: !input cover
mode: restart
